/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as MentorDashboardRouteImport } from './routes/mentor-dashboard'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as SimulateRouteImport } from './routes/simulate'
import { Route as MentorsIndexRouteImport } from './routes/mentors.index'
import { Route as MentorsMentorIdRouteImport } from './routes/mentors.$mentorId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorDashboardRoute = MentorDashboardRouteImport.update({
  id: '/mentor-dashboard',
  path: '/mentor-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulateRoute = SimulateRouteImport.update({
  id: '/simulate',
  path: '/simulate',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsIndexRoute = MentorsIndexRouteImport.update({
  id: '/mentors/',
  path: '/mentors/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsMentorIdRoute = MentorsMentorIdRouteImport.update({
  id: '/mentors/$mentorId',
  path: '/mentors/$mentorId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/mentor-dashboard': typeof MentorDashboardRoute
  '/methodology': typeof MethodologyRoute
  '/opportunities': typeof OpportunitiesRoute
  '/simulate': typeof SimulateRoute
  '/mentors/$mentorId': typeof MentorsMentorIdRoute
  '/mentors/': typeof MentorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/mentor-dashboard': typeof MentorDashboardRoute
  '/methodology': typeof MethodologyRoute
  '/opportunities': typeof OpportunitiesRoute
  '/simulate': typeof SimulateRoute
  '/mentors/$mentorId': typeof MentorsMentorIdRoute
  '/mentors': typeof MentorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/mentor-dashboard': typeof MentorDashboardRoute
  '/methodology': typeof MethodologyRoute
  '/opportunities': typeof OpportunitiesRoute
  '/simulate': typeof SimulateRoute
  '/mentors/$mentorId': typeof MentorsMentorIdRoute
  '/mentors/': typeof MentorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/insights'
    | '/mentor-dashboard'
    | '/methodology'
    | '/opportunities'
    | '/simulate'
    | '/mentors/$mentorId'
    | '/mentors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/insights'
    | '/mentor-dashboard'
    | '/methodology'
    | '/opportunities'
    | '/simulate'
    | '/mentors/$mentorId'
    | '/mentors'
  id:
    | '__root__'
    | '/'
    | '/insights'
    | '/mentor-dashboard'
    | '/methodology'
    | '/opportunities'
    | '/simulate'
    | '/mentors/$mentorId'
    | '/mentors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InsightsRoute: typeof InsightsRoute
  MentorDashboardRoute: typeof MentorDashboardRoute
  MethodologyRoute: typeof MethodologyRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  SimulateRoute: typeof SimulateRoute
  MentorsMentorIdRoute: typeof MentorsMentorIdRoute
  MentorsIndexRoute: typeof MentorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor-dashboard': {
      id: '/mentor-dashboard'
      path: '/mentor-dashboard'
      fullPath: '/mentor-dashboard'
      preLoaderRoute: typeof MentorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulate': {
      id: '/simulate'
      path: '/simulate'
      fullPath: '/simulate'
      preLoaderRoute: typeof SimulateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors/': {
      id: '/mentors/'
      path: '/mentors'
      fullPath: '/mentors/'
      preLoaderRoute: typeof MentorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors/$mentorId': {
      id: '/mentors/$mentorId'
      path: '/mentors/$mentorId'
      fullPath: '/mentors/$mentorId'
      preLoaderRoute: typeof MentorsMentorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InsightsRoute: InsightsRoute,
  MentorDashboardRoute: MentorDashboardRoute,
  MethodologyRoute: MethodologyRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  SimulateRoute: SimulateRoute,
  MentorsMentorIdRoute: MentorsMentorIdRoute,
  MentorsIndexRoute: MentorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
